### ISSUE TITLE
Shared access instead of exclusive?

### ISSUE THREAD

**Issue by nahaff** [Legion2/open-cue-service#24]
Is it possible to add a parameter to start the service with shared access to the iCUE SDK rather than exclusive access? The service works great, but iCUE reports another app has exclusive SDK access. I imagine having this service running would make other iCUE SDK supported games fail to use the iCUE SDK. This isn't really an issue for me right now, but I might want games to have SDK access if I ever got a Corsair keyboard.

Great work BTW! It feels like they purposely hobbled iCUE to sell more Nexus devices, but I need control over the network anyway. The Windows Game Bar Widget appears to use some undocumented part of the SDK to change profiles that are in the UI.

**Comment by Legion2** [comment]
I will look into it, for now you can use the [`/api/sdk/control/false`](https://legion2.github.io/open-cue-service/#/Sdk/Sdk_Control) endpoint to disable the sdk while the service is running.

**Comment by Legion2** [comment]
Looks like the Game SDK does not support to select the access mode.
https://github.com/Legion2/open-cue-service/blob/557c5e15d7d4f1c6c2a43c1bc026ce0734721959/src/CgSdk/CgSdkInterop.cs#L20

The normal corsair SDK have [multiple access modes and support multiple clients](https://corsairofficial.github.io/cue-sdk/#multiple-clients-using-the-sdk-at-the-same-time).

When we compare the two SDKs we see that [`CorsairRequestControl`](https://corsairofficial.github.io/cue-sdk/#corsairrequestcontrol) is optional for the normal SDK, so it also works in shared mode. But for the game sdk, we have to call `RequestControl` else it does not work. So I think the game sdk always needs the exclusive access mode. But this is only based on the reverse engineered information, I don't have the official documentation for the game SDK.
