### ISSUE TITLE
Executable seems to ignore config

### ISSUE THREAD

**Issue by Malspherus** [Legion2/open-cue-service#42]
The executable seems to ignore the `appsettings.json`. I have extracted both files in the same directory. As I understood from the documentation that should be all that is necessary, but even when setting `ProfilesDirectoryName` to a wrong name the executable still uses the default instead of throwing an error.

**Comment by Legion2** [comment]
This is strange I tested it on my PC and if I change the value the crashes with an error message. The extracted directory looks like the following for me:
![image](https://user-images.githubusercontent.com/12752323/140664252-1fc3d07c-60d0-4bc4-a02a-4c20f2be2f01.png)

**Comment by Malspherus** [comment]
I have the same three files together in a folder under `C:\Users\Peter\Scripte\open-cue-service`. I also tried starting the exe from both admin and normal console with the same result.

appsettings.json:
```
{
  "ProfilesDirectoryName": "wrongName",
  "AutoSyncProfileName": "",
  "AutoSyncInterval": 10,
  "StartProfileName": "Standard",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "10.0.0.11"
}
```

Console:
![grafik](https://user-images.githubusercontent.com/5000275/140666986-fc54a17d-4153-402e-848f-1c4162958a9f.png)

Website works and `GET /api​/profiles` returns profiles from `profiles` directory.

Also, it would be great if you could tell me what formats AllowedHosts accepts, I wasn't able to find it anywhere.

**Comment by Legion2** [comment]
Which version of open-cue-service and iCUE do you use?

**Comment by Legion2** [comment]
`AllowedHosts` is the hostname of the machine open-cue-service is running on. However, the http server is only available on localhost for security. If you would like to expose it, you need an reverse proxy.

**Comment by Malspherus** [comment]
iCue:
![grafik](https://user-images.githubusercontent.com/5000275/140761490-b6b9bd9a-dd23-401a-bd2e-a86fd9a910cb.png)

open-cue-service:
![grafik](https://user-images.githubusercontent.com/5000275/140761669-641893d5-8627-41b9-ace4-ba2de0c8d7a6.png)

In that case it might actually be preferable for me to use your [mqtt-version](https://github.com/Legion2/open-cue-mqtt) where I don't need additional services. After all I just want to integrate it into Openhab as easily as possible 😊
If you want to investigate this issue further let me know what you need, I'll also keep the service for now.

**Comment by Legion2** [comment]
The MQTT project is only an adapter, you will still need the open-cue-service. I also use it to control it via Openhab.

I can't repoduce your problem and if it is not a problem for you to use the default directory you can close this issue.

**Comment by Malspherus** [comment]
Oh, I thought MQTT uses the CLI directly, ty for pointing that out.

I was able to find the problem. When running the service (or mqtt) from console you have to be careful to change into the directory first and not just drag & drop the file into the console as I did. The executables search for the config in your the current folder (which was `C:\WINDOWS\system32` in the screenshot), not the one the executable is in. Now everything seems to work as configured 👍

**Comment by Legion2** [comment]
> The executables search for the config in your the current folder

Ok good to know.
The CLI is only a client for the REST API service. Because there must always be a service running to control iCUE, else iCUE will go back into normal mode.
