### ISSUE TITLE
Please update to support iCue version 5.X

### ISSUE THREAD

**Issue by rEd2k** [Legion2/open-cue-service#70]
This is just a request, I love the command line software you made, I am really hoping you will be willing to update it to support the latest iCue version 5.x Thank you for your time and consideration.

**Comment by hasteagag** [comment]
agreed.  I think and I havent created a PR, but I think all that maybe needs to be done is change four to five here 
https://github.com/Legion2/open-cue-service/blob/5c28e7e7cc45eb77b873500a4922859cf473698d/src/ProfileManager.cs#LL12C1-L13C1 

but I dont _have a kotlin compiler installed but might give it a go_ couldnt quite figure out how to compile the service exe (c sharp) in visual studio but it seemed to build no problem.

**Comment by Legion2** [comment]
Does the directory exist with the `CUE5` and is the directory structure the same as before?

**Comment by Legion2** [comment]
Looks like that is the only change that needed, I need to get a hand an a windows computer to verify this.

**Comment by Legion2** [comment]
I created https://github.com/Legion2/open-cue-service/pull/73, the CI build should produce an executable which you can test if it works with CUE5.

**Comment by Legion2** [comment]
Fixed by #73, I release the update 1.1.0

**Comment by hasteagag** [comment]
Thanks so much for releasing this change so quick, sending cookie money.  Would suggest perhaps installed version detect and change that ref to the profile directory.  Alternatively, I suppose we might have been able to make a junction.  Perhaps to future proof this, or so its compatible with 3, 4 and 5, maybe the GameSDKDirectory could be in profiles.json so user can config?

**Comment by Legion2** [comment]
Thanks. Your suggestion sounds good but we never know what will change/break in a future version.

**Comment by rEd2k** [comment]
Thank you good sir, I will try this out soon. I / we really appreciate it!

Edit: Just gave it a try, and it works perfectly like previous versions, thanks again!
